spring.application.name=BACKend
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

twilio.account.sid=${twilio_account_sid}
twilio.auth.token=${twilio_auth_token}
twilio.phone.number=${twilio_phone_number}